apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 26.11.4
    helm:
      releaseName: kafka-cluster
      values: |
        image:
          registry: docker.io
          repository: bitnami/kafka
          tag: 3.6.1-debian-12-r14
        kraft:
          enabled: true
        controller:
          replicaCount: 1
          persistence:
            enabled: false
        broker:
          replicaCount: 1
          persistence:
            enabled: false
        listeners:
          client:
            protocol: PLAINTEXT
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true