apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 22.1.3
    helm:
      releaseName: kafka-cluster
      values: |
        image:
          pullPolicy: IfNotPresent
        kraft:
          enabled: false
        replicaCount: 1
        persistence:
          enabled: false
        zookeeper:
          enabled: true
          persistence:
            enabled: false
        deleteTopicEnable: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true