apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 26.x.x
    helm:
      releaseName: kafka-cluster
      values: |
        # Switching to KRaft mode (No Zookeeper) to fix validation errors
        kraft:
          enabled: true
        zookeeper:
          enabled: false
        controller:
          replicaCount: 1
        broker:
          replicaCount: 1
        listeners:
          client:
            protocol: PLAINTEXT
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true