apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 20.x.x
    helm:
      releaseName: redis-cluster
      values: |
        architecture: replication
        auth:
          enabled: false
        # Fixed: Explicitly setting the tag to avoid "NotFound" errors
        image:
          registry: docker.io
          repository: bitnami/redis
          tag: 7.4-debian-12
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true