apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Repository URL'niz
    repoURL: [https://github.com/Talhadmr/ArgoCD-as-app-of-apps.git](https://github.com/Talhadmr/ArgoCD-as-app-of-apps.git)
    targetRevision: HEAD
    # Git reponuzdaki child app'lerin bulunduğu yol
    path: gitops/apps
  destination:
    server: [https://kubernetes.default.svc](https://kubernetes.default.svc)
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
